#!/bin/bash
#SBATCH --output=std.out
#SBATCH --error=std.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-socket=1
#SBATCH --cpus-per-task=16
#SBATCH --distribution=block:block
#SBATCH --time=168:00:00 #Maximum 7 days
#SBATCH --mem-per-cpu=4gb
#SBATCH --mail-type=NONE
#SBATCH --mail-user=chapagaip@ufl.edu
#SBATCH --partition=gpu
#SBATCH --gpus=a100:1


module load cuda/11.0.207 intel/2020.0.166 namd/3.0

echo "NAMD3                = $(which namd3)"
echo "SBATCH_CPU_BIND_LIST = $SBATCH_CPU_BIND_LIST"
echo "SBATCH_CPU_BIND      = $SBATCH_CPU_BIND     "
echo "CUDA_VISIBLE_DEVICES = $CUDA_VISIBLE_DEVICES"
echo "SLURM_CPUS_PER_TASK  = $SLURM_CPUS_PER_TASK "

gpuList=$(echo $CUDA_VISIBLE_DEVICES | sed -e 's/,/ /g')
N=0
devList=""
for gpu in $gpuList
do
    devList="$devList $N"
    N=$(($N + 1))
done
devList=$(echo $devList | sed -e 's/ /,/g')
echo "devList = $devList"

#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList step4_equilibration.inp > step4_equilibration.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList step5_production.inp > step5_production.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 60-100ns.inp > 60-100ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 100-150ns.inp > 100-150ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 150-200ns.inp > 150-200ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 550-600ns.inp > 550-600ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 600-650ns.inp > 600-650ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 650-700ns.inp > 650-700ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 700-750ns.inp > 700-750ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 750-800ns.inp > 750-800ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList RAMD-MD-10ns.inp > RAMD-MD-10ns.log
namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList RAMD-MD-10-20ns.inp > RAMD-MD-10-20ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 900-950ns.inp > 900-950ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList 950-1000ns.inp > 950-1000ns.log



#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_280-300ns.inp > md3_280-300ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_300-320ns.inp > md3_300-320ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_320-340ns.inp > md3_320-340ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_340-360ns.inp > md3_340-360ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_200-250ns.inp > md3_200-250ns.log     
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_250-300ns.inp > md3_250-300ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_400-500ns.inp > md3_400-500ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_300-350ns.inp > md3_300-350ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_350-400ns.inp > md3_350-400ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_400-450ns.inp > md3_400-450ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_450-500ns.inp > md3_450-500ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_500-550ns.inp > md3_500-550ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_550-600ns.inp > md3_550-600ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_600-650ns.inp > md3_600-650ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_650-700ns.inp > md3_650-700ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_700-750ns.inp > md3_700-750ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_750-800ns.inp > md3_750-800ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_800-850ns.inp > md3_800-850ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_850-900ns.inp > md3_850-900ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_900-950ns.inp > md3_900-950ns.log
#namd3 +p$SLURM_CPUS_PER_TASK +idlepoll +devices $devList md3_950-1000ns.inp > md3_950-1000ns.log
date 


